language: python

python:
  - "3.5"

sudo: false

services:
  - mysql

addons:
  apt:
    packages:
    - liblua5.1-dev
    - libffi-dev

install:
  - cp config.example.py config.py
  - "pip install --upgrade pip"
  - "pip install --trusted-host content.dev.faforever.com -r requirements.txt"
  - "pip install -e db"

before_script:
  - "mysql -e 'create database faf_test;'"
  - "mysql -uroot faf_test < db/db-structure.sql"
  - "mysql -uroot faf_test < db/db-data.sql"

script:
  - pip install -e .
  - py.test --cov-report term-missing --cov=api
  - pyflakes . || true

after_success:
  - coveralls
